name: Unit Test

on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: [ubuntu-20.04]
    strategy:
      matrix:
        node-version: [18.17.0]
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Nest.js test
        run: |
          yarn install
          yarn test:cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
